# Generated by Django 5.0 on 2023-12-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_paises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paises',
            old_name='nompbre',
            new_name='nombre',
        ),
    ]
